
workflows:
  ios-release:
    name: Build iOS release IPA (unsigned)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - swwe6m@gmail.com
